VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="Laam Coin"
ORG_URL="https://laam.online"
ORG_LOGO="https://fond-magenta-owpureihfj.edgeone.app/20250802_225108.png"
ORG_DESCRIPTION="Laam is a native token built on Stellar, designed to be a modern solution for digital currency. It has a fixed max supply of 1,335,577 LAAM — minted only once to preserve scarcity and long-term value."

[[CURRENCIES]]
code="LAAM"
issuer="GAL4ECDAXNBMJYFCWIJ32HKVIRLCNEXY664CAZYI3EINQWPLXTMEPR64"
display_decimals=2
is_asset_anchored=false
name="Laam"
desc="Native token on Stellar with fixed supply: 1,335,577 LAAM"
image="https://fond-magenta-owpureihfj.edgeone.app/20250802_225108.png"
